device_id = "c6bf9d22-a1ea-4e55-8dd7-c822e45a2655"
access_token = "bb6e1112-1349-447b-acb1-2a676eeb449d"
cert_pem = ""
key_pem = ""
ipv4 = "172.16.0.2"
ipv6 = "2606:4700:110:82b0:d8be:738a:8457:cbde"
wg_private_key = "cPdMogkXIxpWjRtckNwWXD1XXX83A9ieNCHSpAUqe1c="
wg_peer_public_key = "bmXOC+F1FxEMF9dyiK2H5/1SUtzH0JuVo51h2wPfgyo="
client_id = "oeP8"
